vich_uploader:
  db_driver: orm
  storage: flysystem

  mappings:
    videos:
      uri_prefix: '%upload_dir%'
      upload_destination: 'aws.storage'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
